### ISSUE TITLE
不支持   linux ? 还是我配置有错

### ISSUE THREAD

**Issue by yangyang5214** [Sean10/vscode-upload-tencentCOS#1]
以下 是我的配置及操作过程：
1、user settings 
tencentCOS.enable :true 
tencentCOS.secret_id   :"my_id"
tencentCOS.secret_key : "my_key"
tencentCOS.bucket :"my_bucket"
tencentCOS.region:"my_regin"
2、空白区域，alt + u 选择图片。

然后报错：
Failed to upload image. Error:[object Object]

系统  ubuntu , 确定当前选择的图片有权限

**Comment by Sean10** [comment]
不好意思，我测试一下

**Comment by Sean10** [comment]
@yangyang5214 不好意思，我在ubuntu装完之后，没能复现问题。请问是在md格式的文件中启动的选择文件吗？另外那几个参数是否确保无误呢？报错提示信息暂时还不能确保打印出有用的内容……

**Comment by yangyang5214** [comment]
好吧  ！  我也忘记了，后面上传图片自己写脚本了. 不过给你个赞！！！

**Comment by Sean10** [comment]
谢谢啦~好，那就关啦~
